int wildcmp(char *s1, char *s2);
int is_palindrome(char *s);
int check_strlen(char *s);
int check_palindrome(int str, int len, char *p);
int check_prime(int div, int num);
int is_prime_number(int n);
int sqrt_get(int g, int c);
int _sqrt_recursion(int n);
int _pow_recursion(int x, int y);
int factorial(int n);
int _strlen_recursion(char *s);
void _print_rev_recursion(char *s);
void _puts_recursion(char *s);
int _putchar(char c);
